-- ============================================================================
-- SLICE 3a (Samantha approved Migrations A and B, 2026-10-10). Hub project. THE JOURNEY LEARNS A CAREGIVER SUBJECT.
-- Migration A: one subject column on client_journey (client | caregiver), an offer id and an AxisCare caregiver id, and two
--   check constraints so a row can never be both subjects. client_journey_step and client_journey_event are untouched.
--   No grant or policy changes (the tables stay server-only). No existing row changes.
-- Migration B: the caregiver catalog rows, version 1, INACTIVE until Slice 3b's code reads them. Seeded from what the Hub
--   enforces today plus her decisions (1 references, 2 OIG monthly, 3 TB/CPR not seeded, 4 FCSR before participant contact,
--   5 Viventium items verified by any admin as the Staffing Coordinator's task, 7 employment start = orientation completion).
-- Additive and safe to run twice. Rollback: slice3a-rollback.sql (columns dropped only if no caregiver journey exists;
--   catalog rows set active = false; nothing deleted).
-- ============================================================================
alter table public.client_journey add column if not exists subject text not null default 'client';
alter table public.client_journey add column if not exists offer_id text;
alter table public.client_journey add column if not exists axiscare_caregiver_id text;
do $c$ begin
  if not exists (select 1 from pg_constraint where conname = 'cj_subject_kind') then
    alter table public.client_journey add constraint cj_subject_kind check (subject in ('client', 'caregiver'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cj_offer_id_unique') then
    alter table public.client_journey add constraint cj_offer_id_unique unique (offer_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cj_caregiver_id_unique') then
    alter table public.client_journey add constraint cj_caregiver_id_unique unique (axiscare_caregiver_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cj_caregiver_id_digits') then
    alter table public.client_journey add constraint cj_caregiver_id_digits check (axiscare_caregiver_id is null or axiscare_caregiver_id ~ '^\d+$');
  end if;
  -- a client row has a lead or a client id and never an offer or caregiver id; a caregiver row has an offer id and never a lead or client id
  if not exists (select 1 from pg_constraint where conname = 'cj_client_rows_are_clients') then
    alter table public.client_journey add constraint cj_client_rows_are_clients check (subject <> 'client' or (offer_id is null and axiscare_caregiver_id is null));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cj_caregiver_rows_are_caregivers') then
    alter table public.client_journey add constraint cj_caregiver_rows_are_caregivers check (subject <> 'caregiver' or (offer_id is not null and lead_id is null and axiscare_client_id is null));
  end if;
end $c$;
-- the existing person constraint (lead or client id) must not refuse caregiver rows: replace it with the subject-aware one
alter table public.client_journey drop constraint if exists cj_has_a_person;
do $c$ begin
  if not exists (select 1 from pg_constraint where conname = 'cj_has_a_person_or_offer') then
    alter table public.client_journey add constraint cj_has_a_person_or_offer check (lead_id is not null or axiscare_client_id is not null or offer_id is not null);
  end if;
end $c$;
comment on column public.client_journey.subject is '3a · client (the lead-to-active journey) or caregiver (the offer-to-approved-to-work journey); the two never mix (constraints)';
create index if not exists client_journey_by_subject on public.client_journey (subject, status);

-- Migration B: the caregiver catalog, version 1, inactive
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.offer.signed', 1, '{"subject": "caregiver", "title": "Offer letter and position description signed", "stage": "offer", "sort": 10, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "system_fact:job_offers.offer_signed_at,pd_signed_at", "required": true, "active": true, "payers": [], "after": [], "howto": ["Verified from the signed offer record; nothing to do here."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step1.application', 1, '{"subject": "caregiver", "title": "Employee Application signed", "stage": "step1", "sort": 20, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "signed_form:step1_forms.signatures.application", "required": true, "active": true, "payers": [], "after": ["cg.offer.signed"], "howto": ["Verified from the Step 1 record: the typed signature, its time, the form version and fingerprint."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step1.references', 1, '{"subject": "caregiver", "title": "Reference consent signed", "stage": "step1", "sort": 21, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "signed_form:step1_forms.signatures.references", "required": true, "active": true, "payers": [], "after": ["cg.offer.signed"], "howto": ["Verified from the Step 1 record: the typed signature, its time, the form version and fingerprint."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step1.fcra', 1, '{"subject": "caregiver", "title": "Background check disclosure signed (FCRA; draft for counsel)", "stage": "step1", "sort": 22, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "signed_form:step1_forms.signatures.fcra", "required": true, "active": true, "payers": [], "after": ["cg.offer.signed"], "howto": ["Verified from the Step 1 record: the typed signature, its time, the form version and fingerprint."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step1.edl_fcsr', 1, '{"subject": "caregiver", "title": "EDL and FCSR consent signed", "stage": "step1", "sort": 23, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "signed_form:step1_forms.signatures.edl_fcsr", "required": true, "active": true, "payers": [], "after": ["cg.offer.signed"], "howto": ["Verified from the Step 1 record: the typed signature, its time, the form version and fingerprint."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step1.availability', 1, '{"subject": "caregiver", "title": "Availability and scheduling commitment signed", "stage": "step1", "sort": 24, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "signed_form:step1_forms.signatures.availability", "required": true, "active": true, "payers": [], "after": ["cg.offer.signed"], "howto": ["Verified from the Step 1 record: the typed signature, its time, the form version and fingerprint."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step1.experience', 1, '{"subject": "caregiver", "title": "Experience and client matching profile signed", "stage": "step1", "sort": 25, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "signed_form:step1_forms.signatures.experience", "required": true, "active": true, "payers": [], "after": ["cg.offer.signed"], "howto": ["Verified from the Step 1 record: the typed signature, its time, the form version and fingerprint."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step1.vehicle', 1, '{"subject": "caregiver", "title": "Vehicle insurance and transportation standards signed", "stage": "step1", "sort": 26, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "signed_form:step1_forms.signatures.vehicle", "required": true, "active": true, "payers": [], "after": ["cg.offer.signed"], "howto": ["Verified from the Step 1 record: the typed signature, its time, the form version and fingerprint."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.consent.checks', 1, '{"subject": "caregiver", "title": "Consents in place before any check or reference contact", "stage": "step1", "sort": 30, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "signed_form:reference_consent,fcra_disclosure,edl_fcsr_consent", "required": true, "active": true, "payers": [], "after": ["cg.step1.references", "cg.step1.fcra", "cg.step1.edl_fcsr"], "howto": ["No reference ask, check order or FCSR registration before these three signatures. The server refuses without them."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.check.oig', 1, '{"subject": "caregiver", "title": "OIG exclusion check (LEIE)", "stage": "screening", "sort": 40, "owner_role": "staffing_coordinator", "proof": "proof", "permission": "screening", "evidence_required": "result+date+document (the LEIE result file)", "required": true, "active": true, "payers": [], "after": ["cg.consent.checks"], "howto": ["Run OIG on the row; the LEIE result is kept as the evidence. Monthly as agency policy (decision 2)."], "expires_after_days": 30}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.check.edl', 1, '{"subject": "caregiver", "title": "Employee Disqualification List check", "stage": "screening", "sort": 41, "owner_role": "staffing_coordinator", "proof": "proof", "permission": "screening", "evidence_required": "result+date+document (DHSS portal result)", "required": true, "active": true, "payers": [], "after": ["cg.consent.checks"], "howto": ["Search the DHSS EDL portal; record the result with its document. Monthly as agency policy (decision 3)."], "expires_after_days": 30}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.check.fcsr_registration', 1, '{"subject": "caregiver", "title": "Family Care Safety Registry registration", "stage": "screening", "sort": 42, "owner_role": "staffing_coordinator", "proof": "proof", "permission": "screening", "evidence_required": "document (DHSS registration confirmation)", "required": true, "active": true, "payers": [], "after": ["cg.consent.checks"], "howto": ["Register from the Screening desk sheet. Must be done, and the screening must clear, before any participant contact (decision 4). The 15-day deadline is never permission to work."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.check.fcsr', 1, '{"subject": "caregiver", "title": "FCSR background screening clear", "stage": "screening", "sort": 43, "owner_role": "staffing_coordinator", "proof": "proof", "permission": "screening", "evidence_required": "result+date+document", "required": true, "active": true, "payers": [], "after": ["cg.check.fcsr_registration"], "howto": ["Record the screening result with its document. Annual recheck as agency policy."], "expires_after_days": 365}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.check.fingerprints', 1, '{"subject": "caregiver", "title": "Fingerprint check clear (lived outside Missouri in the last five years)", "stage": "screening", "sort": 44, "owner_role": "staffing_coordinator", "proof": "proof", "permission": "screening", "evidence_required": "result+date+document", "required": true, "active": true, "payers": [], "after": ["cg.consent.checks"], "howto": ["Applies only when the Step 1 application says they lived outside Missouri in the last five years."], "applies": {"lived_outside_mo": true}}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.refs.cleared', 1, '{"subject": "caregiver", "title": "References cleared: two positive, at least one professional", "stage": "screening", "sort": 45, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "system_fact:reference slots with status Positive", "required": true, "active": true, "payers": [], "after": ["cg.consent.checks"], "howto": ["Verified from the reference records (decision 1). A conditional or negative reference goes to the supervisor decision."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.approve.advance', 1, '{"subject": "caregiver", "title": "Approved to advance to orientation", "stage": "approval", "sort": 50, "owner_role": "owner", "proof": "confirmed", "permission": "advance", "evidence_required": "confirmed_by:person on the Approve to Advance list, with time", "required": true, "active": true, "payers": [], "after": ["cg.check.oig", "cg.check.edl", "cg.check.fcsr", "cg.refs.cleared"], "howto": ["Only a person named on the Admin page Approve to Advance list. The server refuses anyone else."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.i9_s1', 1, '{"subject": "caregiver", "title": "Viventium Step 2: I-9 Section 1 completed by the employee", "stage": "step2", "sort": 60, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.w4', 1, '{"subject": "caregiver", "title": "Viventium Step 2: Federal W-4 completed", "stage": "step2", "sort": 61, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.mo_w4', 1, '{"subject": "caregiver", "title": "Viventium Step 2: Missouri W-4 completed", "stage": "step2", "sort": 62, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.direct_deposit', 1, '{"subject": "caregiver", "title": "Viventium Step 2: Direct deposit set up", "stage": "step2", "sort": 63, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.handbook', 1, '{"subject": "caregiver", "title": "Viventium Step 2: Employee handbook acknowledged", "stage": "step2", "sort": 64, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.participant_rights', 1, '{"subject": "caregiver", "title": "Viventium Step 2: Participant rights acknowledged (19 CSR 15-7.021(24)(B)5)", "stage": "step2", "sort": 65, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.code_of_ethics', 1, '{"subject": "caregiver", "title": "Viventium Step 2: Code of ethics acknowledged", "stage": "step2", "sort": 66, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.confidentiality', 1, '{"subject": "caregiver", "title": "Viventium Step 2: Confidentiality and HIPAA acknowledged", "stage": "step2", "sort": 67, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.license_upload', 1, '{"subject": "caregiver", "title": "Viventium Step 2: Driver license or ID uploaded", "stage": "step2", "sort": 68, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.step2.ss_card_upload', 1, '{"subject": "caregiver", "title": "Viventium Step 2: Social Security card uploaded", "stage": "step2", "sort": 69, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "verified_in_viventium:by a named office person, with time", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": ["Open Viventium, confirm this item exists and is signed, then tick it here with your name. Never inferred from an active payroll record (decision 5: all admins may verify; it is the Staffing Coordinator''s task)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.i9.section2', 1, '{"subject": "caregiver", "title": "I-9 Section 2 completed by an authorized representative", "stage": "step2", "sort": 70, "owner_role": "staffing_coordinator", "proof": "confirmed", "permission": "office", "evidence_required": "confirmed_by:the person who examined the documents, with time; its own tick, never the Step 2 batch", "required": true, "active": true, "payers": [], "after": ["cg.step2.i9_s1"], "howto": ["The person who examined the documents ticks this one themselves (decision 5)."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.welcome.call', 1, '{"subject": "caregiver", "title": "Welcome call done", "stage": "orientation", "sort": 80, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "system_fact:welcome_calls", "required": true, "active": true, "payers": [], "after": ["cg.approve.advance"], "howto": []}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.training.orientation', 1, '{"subject": "caregiver", "title": "Agency orientation (2 hours) complete", "stage": "orientation", "sort": 81, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "system_fact:Training completion with certificate", "required": true, "active": true, "payers": [], "after": ["cg.welcome.call"], "howto": ["Employment start date = the date orientation is completed (decision 7). Both this date and the AxisCare hire date are shown; a difference is flagged."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.training.dementia', 1, '{"subject": "caregiver", "title": "Alzheimer''s and dementia care (4 hours) complete before participant contact", "stage": "orientation", "sort": 82, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "system_fact:Training completion with certificate", "required": true, "active": true, "payers": [], "after": ["cg.training.orientation"], "howto": []}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.training.ojt', 1, '{"subject": "caregiver", "title": "On-the-Job Skills Training (6 hours) within 30 days of employment", "stage": "training", "sort": 83, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "system_fact:Training completion", "required": true, "active": true, "payers": [], "after": ["cg.training.orientation"], "howto": ["19 CSR 15-7.021(22)(A): twelve hours within thirty days of employment; employment = orientation completion (decision 7)."], "due": {"days": 30, "from": "cg.training.orientation"}}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.training.annual', 1, '{"subject": "caregiver", "title": "Annual in-service training (5 hours after year one)", "stage": "training", "sort": 84, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "system_fact:in-service records", "required": true, "active": true, "payers": [], "after": ["cg.training.orientation"], "howto": [], "expires_after_days": 365, "applies": {"after_first_year": true}}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.profile.published', 1, '{"subject": "caregiver", "title": "Caregiver profile published (photo required, video optional)", "stage": "orientation", "sort": 85, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "system_fact:caregiver_profiles.published_at", "required": true, "active": true, "payers": [], "after": ["cg.welcome.call"], "howto": []}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.credential.cna_hha', 1, '{"subject": "caregiver", "title": "CNA or HHA credential verified", "stage": "screening", "sort": 90, "owner_role": "staffing_coordinator", "proof": "proof", "permission": "office", "evidence_required": "document+expiry (registry verification)", "required": true, "active": true, "payers": [], "after": ["cg.step1.application"], "howto": ["Applies only when the Step 1 application claims a CNA or HHA credential. Expiry watched."], "applies": {"claims_cna_or_hha": true}}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.credential.driver', 1, '{"subject": "caregiver", "title": "Cleared to drive clients: license, insurance, driving record, transportation training", "stage": "screening", "sort": 91, "owner_role": "staffing_coordinator", "proof": "proof", "permission": "office", "evidence_required": "documents+expiry (license, insurance at Missouri minimums permitting paid-caregiving transport, driving record, training)", "required": true, "active": true, "payers": [], "after": ["cg.step1.vehicle"], "howto": ["Decision 5 (vehicle): never from Step 1 answers alone. The office verifies license, insurance and driving record and approves caregiver and vehicle."], "applies": {"drives_clients": true}}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.approve.work', 1, '{"subject": "caregiver", "title": "Approved to Work (owners only)", "stage": "ready", "sort": 100, "owner_role": "owner", "proof": "confirmed", "permission": "work", "evidence_required": "confirmed_by:person on the Approve to Work list, with exact time", "required": true, "active": true, "payers": [], "after": ["cg.step2.i9_s1", "cg.i9.section2", "cg.training.orientation", "cg.training.dementia", "cg.profile.published", "cg.check.fcsr", "cg.check.edl", "cg.check.oig", "cg.refs.cleared"], "howto": ["No caregiver is marked Approved to Work until every required onboarding, screening, training and policy acknowledgment is complete (her rule). Scheduling stays locked until this stamp."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;
insert into public.client_journey_step_def (key, catalog_version, def, active, updated_by) values ('cg.axiscare.active', 1, '{"subject": "caregiver", "title": "AxisCare status Active, read back", "stage": "ready", "sort": 101, "owner_role": "hub", "proof": "verified", "permission": "hub", "evidence_required": "system_fact:AxisCare caregiver status read after Approve to Work", "required": true, "active": true, "payers": [], "after": ["cg.approve.work"], "howto": ["Written once after Approve to Work, then read back and verified."]}'::jsonb, false, 'seed 3a 2026-10-10') on conflict (key) do nothing;

do $v$ declare n int; begin
  select count(*) into n from public.client_journey_step_def where key like 'cg.%' and active;
  if n > 0 then raise exception '3a self-check: caregiver catalog rows must stay inactive until Slice 3b'; end if;
  if has_table_privilege('authenticated', 'public.client_journey', 'select') or has_table_privilege('anon', 'public.client_journey', 'select') then
    raise exception '3a self-check: the journey tables must stay server-only';
  end if;
end $v$;
