// SLICE 1b: the approved texts render exactly, the fingerprint is stable, the PDF writer makes a real PDF. No network.
import path from 'path'; import fs from 'fs';
const ROOT = path.dirname(new URL(import.meta.url).pathname), FN = path.join(ROOT, 'supabase/functions');
const res = []; const ck = (n, c, note) => res.push([n, !!c, c ? '' : JSON.stringify(note ?? '').slice(0, 300)]);
const D = await import(path.join(FN, '_shared/offer-documents.ts')); const P = await import(path.join(FN, '_shared/simple-pdf.ts'));
const f = { first: 'Test', last: 'Applicant', position: 'Caregiver', pay_rate: 16, classification: 'prn', date: 'October 9, 2026', expires: 'October 20, 2026', issued_by: 'Krystal Land', issued_at: 'October 9, 2026 at 2:14 PM Central' };
const offer = D.offerLetter(f), pd = D.positionDescription(f); const txt = D.canonical(offer), ptxt = D.canonical(pd);
ck('the letter carries the PRN classification and the no-guaranteed-hours language', /Employment classification: PRN \(as-needed\) field caregiver/.test(txt) && /no minimum number of hours per week is guaranteed/.test(txt) && /not a promise of hours/.test(txt));
ck('the hourly rate, paid weekly on Fridays, non-exempt', /Starting Pay: \$16\.00 per hour, paid weekly on Fridays/.test(txt) && /non-exempt, hourly position/.test(txt));
ck('drug screening is in the contingency list, the permissions sentence, and the position description', (txt.match(/drug screening required by Caring Companions' screening policy/g) || []).length === 2 && /drug screening required by Caring Companions' screening policy/.test(ptxt));
ck('the MVR line is conditional on driving, both places', (txt.match(/when your duties include driving/g) || []).length === 2);
ck('Step 1 is sent automatically once the signed offer is saved (no "within a minute")', /sent to you automatically by text and email once your signed offer is saved/.test(txt) && !/within a minute/.test(txt));
ck('welcome video call then orientation link', /book a short welcome video call, and your paid orientation and training link right after it/.test(txt));
ck('seven business days with the expiry date, and the link dying with the offer', /seven \(7\) business days from the date of this letter, through October 20, 2026\. Your signing link expires at the same time\./.test(txt));
ck('at-will paragraph unchanged', /Employment with Caring Companions is at will\. This means that either you or the Company may end the employment relationship at any time, with or without notice, and with or without cause, as permitted by applicable law\./.test(txt));
ck('issued by the staff member with the time; CEO as issuer, no signature', /Issued by Krystal Land, October 9, 2026 at 2:14 PM Central/.test(txt) && /Warmly,\np\|Samantha Troutman, Co-Founder & CEO/.test(txt) && !/Samantha.*Signature/i.test(txt));
ck('the acceptance sentence and version 1', /I accept the employment offer described above and understand that this offer is contingent upon successfully completing all required pre-employment requirements\./.test(txt) && /Document version 1/.test(txt));
ck('the position description: summary, 10 duties, 8 qualifications incl. drug screening, physical, acknowledgment, issued by, version 1', /POSITION SUMMARY/.test(ptxt) && (ptxt.match(/\nli\|/g) || []).length === 18 && /ACKNOWLEDGMENT/.test(ptxt) && /with or without reasonable accommodation\./.test(ptxt) && /Issued by Krystal Land/.test(ptxt) && /Document version 1/.test(ptxt) && !/Supervisor Signature/.test(ptxt));
const f2 = { ...f, classification: 'part_time' }; ck('part-time gets the hours-not-guaranteed paragraph; an unknown classification refuses', /part-time hourly position/.test(D.canonical(D.offerLetter(f2))) && /not a guarantee of hours/.test(D.canonical(D.offerLetter(f2))) && (() => { try { D.offerLetter({ ...f, classification: 'lead' }); return false; } catch { return true; } })());
const fp1 = await D.fingerprint(txt), fp2 = await D.fingerprint(D.canonical(D.offerLetter({ ...f }))), fp3 = await D.fingerprint(D.canonical(D.offerLetter({ ...f, pay_rate: 16.5 })));
ck('the fingerprint is stable for the same person and changes with one term', fp1 === fp2 && fp1 !== fp3 && /^[0-9a-f]{64}$/.test(fp1));
ck('versions are 1 and 1', D.OFFER_DOC_VERSION === 1 && D.PD_DOC_VERSION === 1);
const bytes = P.makePdf([{ k: 'title', t: 'Offer of employment' }, ...offer, { k: 'h', t: 'ELECTRONIC SIGNATURE' }, { k: 'p', t: 'Signed electronically by Test Applicant' }], { title: 'Offer - Test Applicant' });
const s = Buffer.from(bytes).toString('latin1');
ck('the PDF has a header, pages, fonts, a trailer and the text inside', s.startsWith('%PDF-1.4') && /\/Type \/Pages \/Kids \[/.test(s) && /Helvetica-Bold/.test(s) && /%%EOF\s*$/.test(s) && /no minimum number of hours per week is guaranteed/.test(s) && /Signed electronically by Test Applicant/.test(s));
ck('the PDF is deterministic', Buffer.from(P.makePdf([{ k: 'p', t: 'a' }], { title: 't' })).equals(Buffer.from(P.makePdf([{ k: 'p', t: 'a' }], { title: 't' }))));
const two = P.makePdf(Array.from({ length: 120 }, (_, i) => ({ k: 'p', t: 'Line ' + i + ' ' + 'word '.repeat(30) })), { title: 'long' }); ck('a long document spans pages', /\/Count [2-9]/.test(Buffer.from(two).toString('latin1')));
ck('special characters survive as ASCII (no unreadable glyphs)', /2025-2027 Edition/.test(Buffer.from(P.makePdf(pd, { title: 'pd' })).toString('latin1')));
fs.writeFileSync('/tmp/offer_sample.pdf', bytes);
for (const [n, ok, note] of res) console.log((ok ? 'PASS  ' : 'FAIL  ') + n + (ok ? '' : '  ' + note));
const bad = res.filter((x) => !x[1]).length; console.log(`${res.length - bad}/${res.length} passed`); process.exit(bad ? 1 : 0);
