// SLICE 2a: the Step 1 forms as versioned code, against Samantha's rulings of October 9 (sections 18 to 21 and her seven
// decisions). No network. node step1_documents_558_test.mjs
import path from 'path';
const FN = path.join(path.dirname(new URL(import.meta.url).pathname), 'supabase/functions');
const D = await import(path.join(FN, '_shared/step1-documents.ts')); const C = await import(path.join(FN, '_shared/step1-crypto.ts'));
const res = []; const ck = (n, c, note) => res.push([n, !!c, c ? '' : JSON.stringify(note ?? '').slice(0, 300)]);
const all = D.FORM_ORDER.map((k) => D.formText(k)).join('\n');
ck('seven forms in the eight-screen order; six at version 2 after her form decisions, the FCRA draft at version 1', D.FORM_ORDER.length === 7 && D.FORM_ORDER.every((k) => D.FORMS[k].version === (k === 'fcra_disclosure' ? 1 : 2)) && D.FORMS.employee_application.screen === '2 and 3' && D.FORMS.vehicle.screen === '8');
ck('nothing is approved for real applicants yet', Object.keys(D.APPROVED_FOR_REAL).length === 0);
ck('the FCRA disclosure is a draft for counsel; the screening consent and the vehicle form are to confirm; the rest proposed', D.FORMS.fcra_disclosure.status === 'draft_for_counsel' && D.FORMS.edl_fcsr_consent.status === 'to_confirm' && D.FORMS.vehicle.status === 'to_confirm' && ['employee_application', 'reference_consent', 'availability', 'experience'].every((k) => D.FORMS[k].status === 'proposed'));
const app = D.formText('employee_application');
ck('Employee Application: no Social Security number or street address on it (they live on 5b), other names kept, lived outside Missouri added, preferred name added', !/SS#|social security/i.test(app) && !/Street Address|Zip Code/.test(app) && /other names you have used/.test(app) && /lived outside Missouri in the last five years/.test(app) && /What should families and the office call you/.test(app));
ck('Employee Application: the three typing mistakes are fixed', /Have you had any moving traffic violations/.test(app) && /pled guilty or no contest/.test(app) && /Date of Conviction/.test(app) && !/Convention|no consent|been had/.test(app));
ck('Employee Application: employers gain role, what you did and may-we-contact; the calm instruction; the not-a-participant line in the certification; the approved drug screening wording', /Your role \/ job title/.test(app) && /May we contact them/.test(app) && /Please check every detail; we use these to verify you/.test(app) && /I am not a participant in the Missouri in-home services program/.test(app) && /any drug screening required by Caring Companions' screening policy/.test(app) && !/pass a drug test/.test(app));
ck('v2: no "violation of the law" line, lawful criminal-history wording, fewer than two employers allowed, E-Verify withheld until confirmed, the I-9 line kept', !/violation of the law/.test(app) && /A conviction is not an automatic bar to employment/.test(app) && /expunged or sealed/.test(app) && /If you have fewer than two, list what you have/.test(app) && !/At least two are required/.test(app) && !/E-Verify/.test(app) && D.E_VERIFY_CONFIRMED === false && /complete a Form I-9/.test(app));
const ref = D.formText('reference_consent');
ck('Reference consent: her decision 1 (two professional, two personal, kept apart, a supervisor may be professional) and decision 2 (the sentence reworded)', D.REFERENCES_REQUIRED.professional === 2 && D.REFERENCES_REQUIRED.personal === 2 && /2 professional references \(a supervisor or manager/.test(ref) && /2 personal references/.test(ref) && /not a relative/.test(ref) && /contact the references I provide and to verify relevant employment information/.test(ref) && !/after working with Troutman/.test(ref));
ck('v2: the broad liability release is gone; the clearing rule stays two positive with at least one professional', !/release all former and current employers/.test(ref) && !/any and all liability/.test(ref) && D.REFERENCE_CLEARANCE.positive === 2 && D.REFERENCE_CLEARANCE.professional === 1);
const fcra = D.formText('fcra_disclosure');
ck('FCRA screen: solely the disclosure and the authorization (no EDL, FCSR, at-will, drug, Checkr or box words)', /Disclosure Regarding Background Investigation/.test(fcra) && /Summary of Your Rights/.test(fcra) && /authorize the Company to obtain consumer reports/.test(fcra) && !/EDL|FCSR|at will|at-will|drug|Checkr|Wellsky|Initial|Quarterly/.test(fcra));
const edl = D.formText('edl_fcsr_consent');
ck('EDL and FCSR screen v2: the EDL check, the FCSR registration and screening, and the rechecks are separate; Missouri requirements cited and labelled, Caring Companions policy labelled with the frequency to confirm; ONE consent sentence; no boxes, no vendor', /Employee Disqualification List \(a Missouri requirement\)/.test(edl) && /19 CSR 15-7\.021\(18\)\(B\)/.test(edl) && /Family Care Safety Registry \(a Missouri requirement\)/.test(edl) && /RSMo 192\.2495/.test(edl) && /Rechecks \(Caring Companions policy\)/.test(edl) && /Frequency to be confirmed by Samantha/.test(edl) && /I consent to the EDL check, the FCSR screening and the rechecks described above/.test(edl) && !/Select one statement|Checkr|Wellsky|Super Criminal/.test(edl) && D.SCREENING_PACKAGE.length === 0);
ck('5b carries the three identity fields, locked, with the plain line on why and how they are kept', /Social Security number/.test(edl) && /Date of birth/.test(edl) && /Street address/.test(edl) && D.FORMS.edl_fcsr_consent.sections.find((s) => s.h === 'For your background checks').items.filter((i) => i.locked).map((i) => i.id).join() === 'ssn,dob' && /kept encrypted on our server, seen only by the office person who orders your checks, and every look is logged/.test(edl));
const av = D.formText('availability');
ck('Availability: live-in gone, the four windows, the text consent line, the AxisCare initials, the 90-day wording kept', !/Live-In|Live-in/.test(av) && /Morning;Afternoon;Evening;Overnight;Not available/.test(av) && /You may text me about shifts and schedules at this number/.test(av) && /\(Initials\)/.test(av) && /first ninety \(90\) days of employment/.test(av) && D.FORMS.availability.signature === 'typed+initials');
ck('v2: the AxisCare instructions are plain (tell the office first, update AxisCare once approved) and no guaranteed hours stays', /I tell the office first, as soon as possible\. Once the office approves the change, I update my availability in the AxisCare app/.test(av) && /does not guarantee any minimum or maximum number of work hours/.test(av));
const ex = D.formText('experience');
ck('Experience: the three levels as written, the ten specialties, the matching facts and languages (section 21), the Level 1 sentence', /Hoyer lift \(if trained\), bedbound clients/.test(ex) && D.SPECIALTIES.length === 10 && /Homes with cats/.test(ex) && /Languages you speak well enough to care for a client/.test(ex) && !/English is assumed/.test(ex) && D.LANGUAGES.includes('English') && D.LANGUAGES.includes('Spanish') && D.FORMS.experience.sections.find((s) => s.h === 'Homes and clients you are comfortable with').items.find((i) => i.id === 'languages').kind === 'multi' && /Everyone starts at Level 1/.test(ex) && !D.MATCHING_FACTS.some((m) => /live|payor|medicaid|private pay/i.test(m.id)));
const ve = D.formText('vehicle');
ck('Vehicle: license number, state and expiry (locked), proof as two options incl. "I will provide" (decision 5), the photo optional, the two-choice acknowledgment, driving only after verification', /Driver's license number/.test(ve) && D.FORMS.vehicle.sections[0].items.find((i) => i.id === 'license_number').locked === true && /I will provide proof of current personal automobile insurance coverage to Caring Companions before orientation/.test(ve) && D.FORMS.vehicle.sections[0].items.find((i) => i.id === 'insurance_photo').required === false && /sign a Non-Driver Agreement/.test(ve) && /Driving duties are assigned only after the office has verified my license, insurance and Motor Vehicle Record/.test(ve));
ck('v2: the indemnification clause is gone; coverage and transportation restrictions marked to confirm; the Non-Driver workflow is conditional and stated', !/indemnify and hold harmless/.test(ve) && /Coverage requirement to be confirmed by Samantha/.test(ve) && /Transportation restrictions to be confirmed by Samantha/.test(ve) && /the office will send you the Non-Driver Agreement to sign with your Step 2 paperwork/.test(ve) && D.FORMS.vehicle.status === 'to_confirm');
ck('no em dash anywhere in the texts', !/—/.test(all));
const fp1 = await D.formFingerprint('availability'), fp2 = await D.formFingerprint('availability'), fp3 = await D.formFingerprint('experience');
ck('a form\'s wording has a stable fingerprint, different per form', fp1 === fp2 && fp1 !== fp3 && /^[0-9a-f]{64}$/.test(fp1));
// the lock
const KEK = Buffer.from(new Uint8Array(32).map((_, i) => i * 7 % 256)).toString('base64');
const s1 = await C.seal(KEK, 'offer-1', '123-45-6789'), s2 = await C.seal(KEK, 'offer-1', '123-45-6789');
ck('sealing is random (two seals differ) and opens back to the value', s1 !== s2 && (await C.open(KEK, 'offer-1', s1)) === '123-45-6789' && s1.startsWith('v1.'));
let moved = false; try { await C.open(KEK, 'offer-2', s1); moved = true; } catch { moved = false; }
ck('a sealed value cannot be moved to another offer', moved === false);
let wrong = false; try { await C.open(Buffer.alloc(32, 1).toString('base64'), 'offer-1', s1); wrong = true; } catch { wrong = false; }
ck('a wrong key opens nothing', wrong === false);
ck('last four and the SSN shape check', C.last4('123-45-6789') === '6789' && C.ssnLooksValid('123-45-6789') === false && C.ssnLooksValid('529-12-3456') === true && C.ssnLooksValid('000-12-3456') === false && C.ssnLooksValid('111-11-1111') === false && C.ssnLooksValid('529-00-3456') === false);
for (const [n, ok, note] of res) console.log((ok ? 'PASS  ' : 'FAIL  ') + n + (ok ? '' : '  ' + note));
const bad = res.filter((x) => !x[1]).length; console.log(`${res.length - bad}/${res.length} passed`); process.exit(bad ? 1 : 0);
