// Build-time helper (node tools/brand-assets/build.mjs; run once, output committed): reads the Poppins TTFs and the logo, writes _shared/brand-assets.ts
// with base64 font data + WinAnsi widths, and the logo as a JPEG. Nothing here runs on the server.
import fs from 'fs';
import path from 'path'; import { fileURLToPath } from 'url';
const SC = path.dirname(fileURLToPath(import.meta.url)); const OUT = path.join(SC, '..', '..', 'supabase', 'functions', '_shared', 'brand-assets.ts');
function parseTtf(buf) {
  const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength); const numTables = dv.getUint16(4); const tables = {};
  for (let i = 0; i < numTables; i++) { const o = 12 + i * 16; const tag = String.fromCharCode(buf[o], buf[o + 1], buf[o + 2], buf[o + 3]); tables[tag] = { off: dv.getUint32(o + 8), len: dv.getUint32(o + 12) }; }
  const head = tables.head.off, unitsPerEm = dv.getUint16(head + 18);
  const xMin = dv.getInt16(head + 36), yMin = dv.getInt16(head + 38), xMax = dv.getInt16(head + 40), yMax = dv.getInt16(head + 42);
  const hhea = tables.hhea.off, ascent = dv.getInt16(hhea + 4), descent = dv.getInt16(hhea + 6), numH = dv.getUint16(hhea + 34);
  const hmtx = tables.hmtx.off; const adv = (g) => dv.getUint16(hmtx + Math.min(g, numH - 1) * 4);
  const os2 = tables['OS/2'] ? tables['OS/2'].off : 0; const capHeight = os2 ? dv.getInt16(os2 + 88) : Math.round(unitsPerEm * 0.7);
  const post = tables.post ? tables.post.off : 0; const italicAngle = post ? dv.getInt32(post + 4) / 65536 : 0;
  // cmap format 4 (platform 3, encoding 1)
  const cmap = tables.cmap.off, n = dv.getUint16(cmap + 2); let sub = 0;
  for (let i = 0; i < n; i++) { const pid = dv.getUint16(cmap + 4 + i * 8), eid = dv.getUint16(cmap + 6 + i * 8), off = dv.getUint32(cmap + 8 + i * 8); if (pid === 3 && (eid === 1 || eid === 0)) sub = cmap + off; }
  const segX2 = dv.getUint16(sub + 6), segs = segX2 / 2; const ends = sub + 14, starts = ends + segX2 + 2, deltas = starts + segX2, ranges = deltas + segX2;
  const glyph = (c) => { for (let s = 0; s < segs; s++) { const end = dv.getUint16(ends + s * 2), start = dv.getUint16(starts + s * 2); if (c < start || c > end) continue; const delta = dv.getInt16(deltas + s * 2), ro = dv.getUint16(ranges + s * 2); if (ro === 0) return (c + delta) & 0xffff; const gi = dv.getUint16(ranges + s * 2 + ro + (c - start) * 2); return gi ? (gi + delta) & 0xffff : 0; } return 0; };
  // WinAnsi (cp1252) code -> unicode
  const cp1252 = { 128: 0x20ac, 130: 0x201a, 131: 0x192, 132: 0x201e, 133: 0x2026, 134: 0x2020, 135: 0x2021, 136: 0x2c6, 137: 0x2030, 138: 0x160, 139: 0x2039, 140: 0x152, 142: 0x17d, 145: 0x2018, 146: 0x2019, 147: 0x201c, 148: 0x201d, 149: 0x2022, 150: 0x2013, 151: 0x2014, 152: 0x2dc, 153: 0x2122, 154: 0x161, 155: 0x203a, 156: 0x153, 158: 0x17e, 159: 0x178 };
  const widths = []; for (let c = 32; c <= 255; c++) { const u = cp1252[c] ?? c; const g = glyph(u); widths.push(Math.round(adv(g) * 1000 / unitsPerEm)); }
  return { unitsPerEm, ascent: Math.round(ascent * 1000 / unitsPerEm), descent: Math.round(descent * 1000 / unitsPerEm), capHeight: Math.round(capHeight * 1000 / unitsPerEm), italicAngle, bbox: [xMin, yMin, xMax, yMax].map((v) => Math.round(v * 1000 / unitsPerEm)), widths };
}
let out = `// brand-assets.ts · GENERATED by tools/brand-assets/build.mjs. The Poppins fonts (SIL Open Font License 1.1, Poppins Project Authors)
// and the Caring Companions logo as base64, with the font metrics the PDF writer needs (WinAnsi widths in 1/1000 em).
// Do not edit by hand; regenerate with the build script.\n`;
for (const w of ['Regular', 'SemiBold', 'Bold']) {
  const buf = fs.readFileSync(`${SC}/Poppins-${w}.ttf`); const m = parseTtf(buf);
  out += `export const POPPINS_${w.toUpperCase()} = { name: 'Poppins-${w}', ${JSON.stringify(m).slice(1, -1)}, data: '${buf.toString('base64')}' }\n`;
  console.log(w, 'unitsPerEm', m.unitsPerEm, 'space width', m.widths[0], 'A', m.widths[33], 'bytes', buf.length);
}
const logo = fs.readFileSync(`${SC}/logo.jpg`); const dims = JSON.parse(fs.readFileSync(`${SC}/logo.json`));
out += `export const LOGO_JPEG = { width: ${dims.w}, height: ${dims.h}, data: '${logo.toString('base64')}' }\n`;
fs.writeFileSync(OUT, out); console.log('brand-assets.ts', (out.length / 1024).toFixed(0), 'KB');
